# Doc2Doc needs to be able to find the number of lines in a document that contain a specific sequence of characters. For example, given the following document:

# aaaa
# bbbb
# ccdd
# aabb

# How many lines contain the sequence "aa"? The answer is 2: "aaaa" and "aabb".

# Complete the lines_with_sequence function. It should return a series of curried functions so it can be called like this:

# num_lines = lines_with_sequence(char)(length)(doc)

# The "sequence" is generated by the first with_char that has been provided for you. It works like this:

# Character	Length	Sequence
# "a"	3	"aaa"
# "b"	2	"bb"
# "*"	4	"****"
# You need to define and return a second curried function. I called mine with_length. It should accept the final parameter, a doc string, and return the number of lines that contain the sequence.

# Define the with_length function inside the with_char function, it should accept a doc.
# Split the doc into lines.
# Use a loop (or if you're feeling fancy, import and use reduce) to count the number of lines that contain the sequence in them.
# Return the count from the with_length function.
# Return the with_length function from the with_char function.


# Version 1

def lines_with_sequence1(char):
    def with_char(length):
        def with_length(doc):
            count = 0
            sequence = char * length
            lines = doc.split('\n')
            for line in lines:
                if (sequence in line):
                    count += 1     
            return count
        return with_length
    return with_char




# Version with reduce 
import functools
def lines_with_sequence2(char):
    def with_char(length):
        def with_length(doc):
            sequence = char * length
            lines = doc.split('\n')
            # Reduce takes two arguments 
            def count_sequence(acc, line):
                return acc + (1 if sequence in line else 0)    
            return functools.reduce(count_sequence, lines, 0)
        return with_length
    return with_char




def lines_with_sequence3(char):
    def with_char(length):
        def with_length(doc):
            sequence = char * length
            return functools.reduce(
                lambda acc, line: acc + (1 if sequence in line else 0), 
                doc.split('\n'), 
                0  # initial accumulator
            )
        return with_length
    return with_char